### ISSUE TITLE
URN in permissions.rb has changed

### ISSUE THREAD

**Issue by will-in-wi** [PRX/pmp#8]
It looks like the URN used in the query has changed to `urn:collectiondoc:query:docs`.

Also, could there be better docs about how to query? It took me about 30 minutes to figure it out.

**Comment by kookster** [comment]
thanks.
https://github.com/PRX/pmp/commit/12a3ea2e63f37aa3ad9cb1606cd3d4f678bedcb7

The README is mostly concerned with persistence, I don't do alot of search since my use for this is largely publishing into the pmp.

If you want more example code of using the `pmp` gem, I have several utility functions in here:
https://github.com/PRX/pmp-importer.prx.org/blob/master/app/models/application_importer.rb

which get used here:
https://github.com/PRX/pmp-importer.prx.org/blob/master/app/models/prx_importer.rb

**Comment by kookster** [comment]
ok, updated the readme now too.

you can also find some info about queries in the tests:
https://github.com/PRX/pmp/blob/master/spec/collection_document_spec.rb#L148-L173

**Comment by kookster** [comment]
@will-in-wi is that good enough, can I close this?

**Comment by will-in-wi** [comment]
Yes. If I run into anything else, I'll open new tickets. Thanks!
